"""
features/text_tika.py — Apache Tika Java-based text extraction.

Strategy: text:tika-java

Apache Tika is a Java content analysis toolkit that supports 1000+ file formats.
For PDFs it uses PDFBox under the hood — often better than Python tools for:
  - Complex multi-column layouts
  - PDFs generated by Microsoft Office / LibreOffice  - PDFs with unusual structure or encoding
  - Very old PDF versions

Runtime: The ``tika`` Python package auto-downloads the Tika JAR (~60 MB) on
first use (cached at ~/.tika/) and starts a local JVM server.  Requires Java
in PATH — available via ``default-jre-headless`` in the Docker image.

Notes
-----
- First run is slow (JVM startup + optional JAR download)
- Subsequent runs reuse the running Tika server — much faster
- Language detection is handled by Tika (no langdetect needed)
"""

from __future__ import annotations

from ._base import FeatureResult, PageResult
from ._protocol import StrategyMeta


STRATEGY = StrategyMeta(
    name="text:tika-java",
    tier="text",
    description="Apache Tika (Java/PDFBox) — 1000+ formats, strong for complex layouts",
    module="pdf_extractor.features.text_tika",
    requires_python=["tika"],
    requires_system=["java"],
    priority=40,
)


def extract(pdf_path: str, page_range: tuple[int, int] | None = None) -> FeatureResult:
    result = FeatureResult(feature="text_tika")

    try:
        import tika
        from tika import parser as tika_parser
    except ImportError:
        result.warnings.append("tika not installed; text_tika-java skipped  (pip install tika)")
        return result

    try:
        # Tika returns the full text of the document — no per-page breakdown
        parsed = tika_parser.from_file(pdf_path, requestOptions={"timeout": 120})

        if parsed.get("status") != 200 and not parsed.get("content"):
            result.warnings.append(f"Tika returned status {parsed.get('status')}")
            return result

        full_text: str = (parsed.get("content") or "").strip()
        if not full_text:
            return result

        # Tika metadata extras
        meta = parsed.get("metadata", {})
        result.metadata = {
            "backend": "apache-tika",
            "content_type": meta.get("Content-Type", ""),
            "creator": meta.get("dc:creator", ""),
            "pdf_version": meta.get("pdf:PDFVersion", ""),
        }

        # page_range: Tika doesn't support per-page extraction natively.
        # We fall back to assigning everything to page 1 and flagging it.
        result.pages.append(PageResult(
            page=1,
            content=full_text,
            backend="apache-tika",
            confidence=0.78,
        ))
        result.markdown = full_text
        result.confidence = 0.78

    except Exception as exc:
        result.warnings.append(f"text_tika error: {exc}")

    return result
